[package]
name = "trash"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
foo = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
baer = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
p= { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
foobar = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
pose= { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
posei= { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
poseid= { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
ecrecover = { tag = "v0.8.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
# GitHub dependency in a subdirectory
easy_private_token_contract = { tag = "v0.1.0-alpha62", git = "https://github.com/AztecProtocol/aztec-packages", directory = "noir-contracts/contracts/easy_private_token_contract" }
# Local dependency (relative path)
lib_a = { path = "../lib_a" }
